###########################################
# Monitors
###########################################

# starts the monitors in the right way
exec --no-startup-id xrdb ~/.XResources

# Sets the backgrounds
exec --no-startup-id ~/.config/i3/scripts/fehbg.sh


###########################################
# XDG
###########################################

# Start XDG autostart .desktop files
exec --no-startup-id dex --autostart --environment i3